### ISSUE TITLE
Vocabulary Repository Suggest API is not wrapped in a callback function/no JSPNP formatting

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/LindaWorkbench#178]

**Comment by dipapaspyros** [comment]
Example of calling an API method from a different domain:
```javascript
$.ajax({
        type: 'GET',
        dataType: 'jsonp',
        data: {},
        url: "http://localhost:8000/coreapi/recommend/?q=person&callback=?",
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(jqXHR)
        },
        success: function (msg) {
            console.log(msg);
        }
});
```

**Comment by bbrand84** [comment]
does not work, returns error

the version I used formely is very similar: 

<pre><code>
	$.ajax({
		type: "GET",
		dataType: "jsonp",
		contentType: "application/javascript",
		data: { 'q': term },
		async: false,
		//url: 'http://linda.epu.ntua.gr:8000/coreapi/recommend',
		url: 'http://127.0.0.1:8000/transformation/jsondummy',
		success: callback,
		error: function(xhr, status, error){
 			console.log(error+"\n"+status+"\n"+xhr.responseText);
		},
		beforeSend: function(){
			ev.target.innerHTML="loading...";
		}
	});
</code></pre>

I used it with a dummy json output which was surrounded by a callback function and easily got results. the callback parameter you added to your url did not have any effect on the json output.

am I missing sth?

**Comment by dipapaspyros** [comment]
Does the original version work for you? If yes, maybe it's a problem of your workbench configuration in localhost

**Comment by bbrand84** [comment]
It just occurred to me that I do not have the whole workbench installed and therefore must do a cross domain call to your public Greek server. Of course this problem won't occur if both systems are on the same machine. But I'm still wondering since you provided a callback parameter in your example which does not have any effect...

----- Ursprüngliche Nachricht -----
Von: "Dimitris Papaspyros" <notifications@github.com>
Gesendet: ‎14.‎05.‎2015 10:07
An: "LinDA-tools/LindaWorkbench" <LindaWorkbench@noreply.github.com>
Cc: "bbrand84" <benjaminbrand@gmx.de>
Betreff: Re: [LindaWorkbench] Vocabulary Repository Suggest API is not wrappedin a callback function/no JSPNP formatting (#178)

Does the original version work for you? If yes, maybe it's a problem of your workbench configuration in localhost
